### ISSUE TITLE
Python 3.6 wheels

### ISSUE THREAD

**Issue by jonasrauber** [bashtage/ng-numpy-randomstate#113]
Could you please release wheels for Python 3.6 on PyPI? Installation from source takes really long. Thanks!

**Comment by bashtage** [comment]
OSX?

**Comment by jonasrauber** [comment]
Linux

**Comment by bashtage** [comment]
manylinux wheels seem to be a bit of a pain.  It is more likely that I could build conda packages -- are these useful?

**Comment by jonasrauber** [comment]
No, not using conda. But no problem, installing from source is fine, just would have been nice because I do install it quite regularly (it‘s part of my work environment Dockerfile) and I thought, only 3.6 is missing ;-)

**Comment by bashtage** [comment]
I'm going to leave this open - I did a quick bit of investigation and it may not be hopeless.  Will have to see if I can automate it enough.

**Comment by bashtage** [comment]
I just dropped 1.13.3.  If everything goes to plan there will be Linux wheels for x86_64 and 2.7, 3.5 and 3.6.

Please let me know if these work (they pass the test on the same computer that built them, but this isn't a big surprise)

**Comment by bashtage** [comment]
These have been released.

**Comment by jonasrauber** [comment]
Awesome, works! Thanks a lot :)
