### ISSUE TITLE
PCG64

### ISSUE THREAD

**Issue by rkern** [bashtage/ng-numpy-randomstate#5]
https://github.com/rkern/pcg64

Here is my promised C implementation of PCG64 that incorporates the necessary emulation of `uint128_t` arithmetic when not supported by the C compiler. Not entirely sure how useful this will be for you, but I think it's my preferred candidate for best all-rounder default PRNG.

It "only" supports the settable-sequence variant, but I think that's the one we're actually interested in and dropping the others eliminates a lot of cruft.

**Comment by bashtage** [comment]
Thanks.  Looks reasonable - I think that is the only part of pcg64 that is needed.

**Comment by bashtage** [comment]
Thanks - incorporated without any issues.  Still need to check on a 32 bit VM, but worked as a drop-in replacement for the stock PCG-64
