### ISSUE TITLE
Segfault when seeding some prng's with float64

### ISSUE THREAD

**Issue by superconvergence** [bashtage/ng-numpy-randomstate#82]
When (wrongly..) using floats as a seed value, most PRNGs will segfault (mrg32k3a, xorshift128, xoroshiro128plus, xorshift1024, mlfg_1279_861 and mrg32k3a), some (dsfmt and mt19937) will fail with TypeError (Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe') and some (pcg32, pcg64) will actually work as if int(seed) was given.

Maybe this behavior should be more uniform?
At least the segfaults (killing the interpreter) should not happen in any case.

**Comment by bashtage** [comment]
Thanks.  Can you provide a small code example the reproduces the segfault?

**Comment by superconvergence** [comment]
Sure,
any of the following will segfault on my system:

import randomstate

prng = randomstate.prng.mrg32k3a.RandomState(1.1)
prng = randomstate.prng.xoroshiro128plus.RandomState(1.1)
prng = randomstate.prng.xorshift1024.RandomState(1.1)
prng = randomstate.prng.mlfg_1279_861.RandomState(1.1)
prng = randomstate.prng.mrg32k3a.RandomState(1.1)

I don't currently have access to the system (debian testing if it matters) but, if I remember correctly, it is using numpy 1.12, cython 0.25, and segfaults for both python 2.7 and 3.6. 

Let me know for any other info you might need.

**Comment by bashtage** [comment]
Thanks.

**Comment by bashtage** [comment]
Not sure if closed to leaving open for now.

**Comment by superconvergence** [comment]
Looks OK to me after the latest commit; all generators are now failing gracefully, throwing TypeError.

Thanks!

**Comment by bashtage** [comment]
Thanks.  Closing.
