### ISSUE TITLE
Is there a generic randomstate class I can inherit from?

### ISSUE THREAD

**Issue by nbecker** [bashtage/ng-numpy-randomstate#86]
In this example, I'm using a specific RNG:
```
class shared_random_state (randomstate.prng.xorshift1024.RandomState):
    def __init__ (self, rs):
        randomstate.prng.xorshift1024.RandomState.__init__(self, rs)

    def __deepcopy__ (self, memo):
        return self
```
Is there a more generic way I can write this?

Is there a better forum (gitter?) where I can ask such questions?

**Comment by bashtage** [comment]
What are you trying to do?  Is there something useful missing from the usual RandomState class that __deepcopy__ adds?

**Comment by nbecker** [comment]
I'm making a singleton rs object.  This object will be part of many random number generator objects in my simulation, and I want to ensure they are independent, by making them share a single rs object.

At the top level of the simulation, I have:
    arrival_gens = [deepcopy (opt.arrival_gen) for _ in range (opt.n_carriers)]

where opt.arrival_gen contains buried in it several levels deep, the shared_random_state object.  Overiding __deepcopy__ to return self makes deepcopy produce a shallow copy for the randomstate, so all arrival_gens share a single randomstate.

I guess a better way to write my shared_random_state might be
class shared_random_state (object):
    def __init__ (self, rs):
        self.rs = rs

    def __deepcopy__ (self, memo):
        return self

    def __getattr__(self, name):        # delegate all operations not specifically overridden to rs
        if 'rs' in self.__dict__:      # this is to allow unpickle avoid infinite recursion
            return getattr (self.rs, name)
        raise AttributeError(name)

**Comment by bashtage** [comment]
I saw you closed.  I suppose RandomState could have a correct __deepcopy__ method.
