### ISSUE TITLE
lognormal doc enhancement?

### ISSUE THREAD

**Issue by nbecker** [bashtage/ng-numpy-randomstate#89]
When specifying a lognormal, you may want to specify it in terms of the mean and stddev of the output distribution (not the underlying normal distribution).  The following code allows you to find the mean and stddev parameters to supply to lognormal to get the desired results:
```
from math import log, exp
def sigma_x2 (mu_y, sigma_y):
    return log (1 + exp (2*(log(sigma_y) - log(mu_y))))

def mu_x (mu_y, sigma_y):
    return log(mu_y) - sigma_x2(mu_y, sigma_y)/2
```
the desired output mean and stddev are mu_y and sigma_y: the resulting mu_x and sigma_x2 are the mean and variance to supply to lognormal (use sqrt(sigma_x2) to pass to lognormal as sigma)

**Comment by bashtage** [comment]
Sure, this can be desirable.  The library is, however, tied to the numpy implementation and so this isn't easily changeable.

**Comment by nbecker** [comment]
Just to be clear, I was only suggesting to enhance the documentation
