### ISSUE TITLE
`advance` and `randint`

### ISSUE THREAD

**Issue by mkoerner** [bashtage/ng-numpy-randomstate#94]
When using `advance` in connection with `uniform`, I understand the behavior. Running 

```
import randomstate as rs
g = rs.prng.pcg64.RandomState(0,0)
x = g.uniform(size=10)
g = rs.prng.pcg64.RandomState(0,0)
g.advance(5)
y = g.uniform(size=10)
```

creates random number in `x` and `y` so that `x[5:] == y[:-5]` is `True` for the selected range. When doing the same with `randint`

```
import randomstate as rs
g = rs.prng.pcg64.RandomState(0,0)
x = g.randint(256, size=10)
g = rs.prng.pcg64.RandomState(0,0)
g.advance(5)
y = g.randint(256, size=10)
```

I expected the same behavior, but this is not the case. 

*What is the method used to generate random numbers with `randint`?* I expected one uniform random number to be used for one integral number, but that does not seen to be the case. 

It could be nice to have more documentation on this. Or a better interface for the interaction between `advance` and the functions which create random values. I'm aware that it may only be possible for the functions that use a fixed number of "basic random values" per random value generated.

Thanks,
Mathias

**Comment by bashtage** [comment]
`randint` is efficient in that is uses the smallest number of bytes required to produce the values from the PRNG, and so the dtype affects what you get.  In the case of `int32` it will generate 2 per 64-bit random generated by PCG.

The only generator that is _absolutely guaranteed_ to behave like you see above is `random_raw` since it never will transform the underlying output of the PRNG.  As you have seen, for some distributions this will always work.  For others which use fewer bits (`randint`) or which use rejection sampling (many) then this simple relationship cannot be easily enforced. 

```
g = rs.prng.pcg64.RandomState(0,0)
x = g.random_raw(10)
g = rs.prng.pcg64.RandomState(0,0)
g.advance(5)
y = g.random_raw(10)

import numpy as np
assert np.all(x[5:]==y[:-5])
```

**Comment by bashtage** [comment]
I hope the explanation above is clear.  If not, let me know.  I'll add to the documentation.

**Comment by mkoerner** [comment]
Sorry for not replying earlier. The explanation was helpful. As is more documentation. Given your description, a colleague and myself expected `advance` to "work well" with generating 64-bit random integers, but

```
import randomstate as rs
import numpy as np

g = rs.prng.pcg64.RandomState(0,0)
x = g.randint(256, size=10, dtype=np.uint64)
g = rs.prng.pcg64.RandomState(0,0)
g.advance(5)
y = g.randint(256, size=10, dtype=np.uint64)

assert np.all(x[5:]==y[:-5])
```

also raised an exception.

PS: Do you happen to know, if all bits of the numbers generated by PCG64 of equal quality?

**Comment by bashtage** [comment]
This works as expected:

```python
g = rs.prng.pcg64.RandomState(0,0)
x = g.randint(2**64-1, size=10, dtype=np.uint64)
g = rs.prng.pcg64.RandomState(0,0)
g.advance(5)
y = g.randint(2**64-1, size=10, dtype=np.uint64)

assert np.all(x[5:]==y[:-5])
```

You are seeing the behavior you see because of this optimization:

https://github.com/bashtage/ng-numpy-randomstate/blob/master/randomstate/distributions.c#L1415

which uses 32-bit integers when the value required is < 2**32.

**Comment by bashtage** [comment]
As for `pcg64`, I've never seen any problems when it is run through tests (which test for dependence in high/low bits). This said, If I needed a log of PRNGs I would go with `xorshift1024` with jumps.

**Comment by mkoerner** [comment]
Ah. Thanks again for the clarification.
 ... and for the library 👍

- Mathias
